name: lucento
description: away to share books

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.4+2
  get_it: ^3.0.3
  provider: ^3.2.0
  http: 0.12.0+4
  equatable: ^1.0.1
  dartz: ^0.8.9
  google_fonts: ^0.3.7
  fluttertoast: ^3.1.3
  flutter_screenutil: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true